model:
  type: TwoLevelAmortizedPosterior
  name: covid_amortizer
  summary_net_kwargs:
    local_summary_net:
      summary_dim: 10
      type: TwoLevelSequenceNetwork
    global_summary_net:
      summary_dim: 20
      type: DeepSet
    type: HierarchicalNetwork
  local_amortizer:
    inference_net:
      num_coupling_layers: 10
      coupling_design: spline
      permutation: fixed
      type: InvertibleNetwork
    type: AmortizedPosterior
    name: local_amortizer
  global_amortizer:
    inference_net:
      num_coupling_layers: 10
      coupling_design: spline
      permutation: fixed
      type: InvertibleNetwork
    type: AmortizedPosterior
    name: global_amortizer
task:
  name: test
  description: synthetic data
  output_path: output_mlm
  intervention_model: true
  observation_model: true
  num_samples: 1000000
  T: 81
  n_regions: 4
  mobility_condition_strategy: accumulated_flows
training:
  epochs: 20
  batch_size: 25000
  early_stopping: true
  validation_sims: 2000
  trainer:
    default_lr: 0.0005
    memory: true
    skip_checks: true

  # train_fraction: 0.95
  # optimizer:
  #   lr: 0.0002
  #   type: adam
  # scheduler:
  #   factor: 0.2
  #   patience: 1
  #   type: reduce_on_plateau