build-js:
  stage: build
  before_script:
    - npm install
  script:
    - echo "Building app deployment"
    - npm run build
    - echo "Building done"
  artifacts:
    paths:
      - build/

www:
  stage: deploy
  dependencies:
    - build-js
  script:
    - echo "Deploying to server"
    - cp -rv build/* /var/www/html
    - echo "Deployed"
  only:
    - master
