build-cpp:
  stage: build
  tags:
   - cpp
   - hpcagainstcorona
  before_script:
    - apt -qq -y install libeigen3-dev
  script:
    - cd cpp
    - mkdir build && cd build
    - cmake -G Ninja ..
    - cmake --build .
  artifacts:
    expire_in: 2 hrs
    paths:
      - cpp/build/

build-py:
  tags:
   - cpp
   - hpcagainstcorona
  stage: build
  before_script:
    - apt -qq -y install python3.7-venv python3-venv libeigen3-dev
    - cd pycode
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install scikit-build
  script:
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - pycode/dist/*.whl

# run tests using the binary built before
test-cpp:
  tags:
   - cpp
   - hpcagainstcorona
  stage: test
  dependencies:
    - build-cpp
  script:
    - cd cpp/build/tests
    - ./runUnitTests --gtest_output="xml:report.xml"
  artifacts:
    reports:
      junit: cpp/build/tests/report.xml

test-py:
  tags:
   - cpp
   - hpcagainstcorona
  stage: test
  dependencies:
    - build-py
  before_script:
    - apt -qq -y install python3.7 python3-pip
    - for pkg in `ls pycode/dist/*.whl`; do python3 -m pip install $pkg; done
  script:
    - cd pycode/test
    - python3 -m unittest
    - getrkidata --help
    - getpopuldata --help
    - getjhdata --help
    - getspaindata --help

download-data:
  tags:
   - cpp
   - hpcagainstcorona
  stage: test
  dependencies:
    - build-py
  before_script:
    - apt -qq -y install python3.7 python3-pip
    - for pkg in `ls pycode/dist/*.whl`; do python3 -m pip install $pkg; done
  script:
    - mkdir data
    - getrkidata -o data
    - getpopuldata -o data
    - getjhdata -o data
    - getspaindata -o data
  artifacts:
    paths:
      - data/*.json
  

build-js:
  tags:
   - npm
   - hpcagainstcorona
  stage: build
  before_script:
   - npm install
  script:
    - echo "Building app deployment"
    - npm run build
    - echo "Building done"
  artifacts:
    paths:
      - build/

www:
  tags:
   - native
   - hpcagainstcorona
  stage: deploy
  dependencies:
    - build-js
    - download-data
  script:
    - echo "Deploying to server"
    - cp -rv build/* /var/www/html
    - cp -v data/*.json /var/www/html/assets
    - echo "Deployed"
  only:
    - master
