build-cpp:
  stage: build
  script:
    - cd cpp
    - mkdir build && cd build
    - cmake ..
    - cmake --build .
  artifacts:
    expire_in: 2 hrs
    paths:
      - cpp/build/

build-py:
  stage: build
  script:
    - cd pycode
    - virtualenv venv
    - source venv/bin/activate
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - pycode/dist/*.whl

# run tests using the binary built before
test-cpp:
  stage: test
  dependencies:
    - build-cpp
  script:
    - cd cpp/build/tests
    - ./runUnitTests --gtest_output="xml:report.xml"
  artifacts:
    reports:
      junit: cpp/build/tests/report.xml

build-js:
  stage: build
  before_script:
     - npm install
  script:
    - grunt
  artifacts:
    paths:
      - dist/

www:
  stage: deploy
  dependencies:
    - build-js
  script:
    - cp -r dist/* /var/www/html
  only:
    - master
