name: "Download artifacts"
description: "Get artifacts from epidata CI"
inputs:
  artifact-name:
    description: "Name of the required artifact."
    required: true
  package:
    description: "Package from which to get the artifacts"
    required: true
  secret-token:
    description: "GitHub Token to use gh command in workflow"
    required: true
runs:
  using: "composite"
  steps:
    - name: get artifact
      shell: pwsh
      run: gh run download -n ${{ inputs.artifact-name }}-${{ inputs.package }}
      env:
        GITHUB_TOKEN: ${{ inputs.secret-token }}
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}-${{ inputs.package }}
        retention-days: 1
        path: |
          pycode/coverage_python.xml
          coverage_python
