name: "Build Python Package"
description: "Build one of the MEmilio Python packages. Creates wheel as artifact."
inputs:
  package:
    description: "Package to build."
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        yum install ninja-build -qy
        /opt/python/cp36-cp36m/bin/pip install conan
        /opt/python/cp37-cp37m/bin/pip install conan
        /opt/python/cp38-cp38/bin/pip install conan
    - name: Make artifact dir
      shell: bash
      run: |
        cd pycode/memilio-${{ inputs.package }}/
        mkdir wheelhouse
    - name: Build Python Wheels
      shell: bash
      run: |
        cd pycode/memilio-${{ inputs.package }}/
        /opt/python/cp36-cp36m/bin/python setup.py bdist_wheel -- -DCONAN_COMMAND=/opt/python/cp36-cp36m/conan
        /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel -- -DCONAN_COMMAND=/opt/python/cp37-cp37m/conan
        /opt/python/cp38-cp38/bin/python setup.py bdist_wheel -- -DCONAN_COMMAND=/opt/python/cp36-cp38/conan
        if [[ -f "CMakeLists.txt" ]]; then 
          # includes native dependencies in the wheel
          for whl in dist/*.whl; do auditwheel repair "$whl"; done
        else
          # no auditwheel necessary for pure python packages, so only copy the wheels to the same output directory 
          cp dist/*.whl wheelhouse
        fi
        cp -r wheelhouse ..
    - name: Upload Python Wheels
      uses: actions/upload-artifact@v2
      with:
        name: python-wheels-${{ inputs.package }}
        path: pycode/wheelhouse