name: "Build Python Package"
description: "Build one of the MEmilio Python packages. Creates wheel as artifact."
inputs:
  package:
    description: "Package to build."
    required: true
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        yum install ninja-build -qy
        if [[ "${{ inputs.package }}" == "simulation" ]]; then
          /opt/python/cp37-cp37m/bin/pip install conan
          /opt/python/cp310-cp310/bin/pip install conan
        fi
    - name: Cache Conan packages
      uses: actions/cache@v2
      with:
        path: ~/.conan/data
        key: conan-data-py-${{ inputs.package }}
    - name: Make artifact dir
      shell: bash
      run: |
        cd pycode/memilio-${{ inputs.package }}/
        mkdir wheelhouse
    - name: Build Python Wheels
      shell: bash
      run: |
        cd pycode/memilio-${{ inputs.package }}/
        if [[ "${{ inputs.package }}" == "simulation" ]]; then
          SETUP37ARGS="-DCONAN_COMMAND=/opt/python/cp37-cp37m/bin/conan -DPython_ROOT_DIR=/opt/python/cp37-cp37m"
          SETUP310ARGS="-DCONAN_COMMAND=/opt/python/cp310-cp310/bin/conan -DPython_ROOT_DIR=/opt/python/cp310-cp310"
          #pre-built b2 package (required for building boost) doesn't work on manylinux image
          SETUPARGS="-DPython_FIND_STRATEGY=LOCATION -DMEMILIO_CONAN_BUILD=missing;b2"
        fi
        /opt/python/cp37-cp37m/bin/python setup.py bdist_wheel -- $SETUP37ARGS $SETUPARGS
        /opt/python/cp310-cp310/bin/python setup.py bdist_wheel -- $SETUP310ARGS $SETUPARGS
        if [[ -f "CMakeLists.txt" ]]; then 
          # includes native dependencies in the wheel
          for whl in dist/*.whl; do auditwheel repair "$whl"; done
        else
          # no auditwheel necessary for pure python packages, so only copy the wheels to the same output directory 
          cp dist/*.whl wheelhouse
        fi
        cp -r wheelhouse ..
    - name: Upload Python Wheels
      uses: actions/upload-artifact@v2
      with:
        name: python-wheels-${{ inputs.package }}
        path: pycode/wheelhouse