name: "Linux Examples"
description: "Run the C++ examples on linux."
inputs:
  build-artifact:
    description: "Name of the build artifact that contains the unit test binary."
    required: true
runs:
  using: "composite"
  steps:
    # taken from https://github.com/actions/runner-images/issues/9524#issuecomment-2002475952
    - name: Fix kernel mmap rnd bits
      shell: bash
      # Asan in llvm 14 provided in ubuntu 22.04 is incompatible with
      # high-entropy ASLR in much newer kernels that GitHub runners are
      # using leading to random crashes: https://reviews.llvm.org/D148280
      run: sudo sysctl vm.mmap_rnd_bits=28
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get -qq update
        sudo apt-get -qq -y install libhdf5-10* wget gnupg lcov
        sudo apt-get -qq update
    - name: Download examples directory
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact }}
        path: cpp
    - name: extract examples archive
      shell: bash
      run: |
        cd cpp
        tar -xzf build.tar.gz
    - name: Run examples
      shell: bash
      run: |
        cd cpp/build/bin
        sudo chmod -R a+x ./
        numberoffiles=$(ls -dq *_example | wc -l)
        if [[ "$numberoffiles" -gt "0" ]]; then 
          echo "Running Linux examples."
          find . -name "*_example" -print0  | xargs -0 -n1 -P 1 -t bash -c || exit 1   
        else
          echo "No Files found with name _example, abort."
          exit 1
        fi
