name: "Build MSVC"
description: "Build memilio c++ library using MSVC on Windows"
inputs:
  config: 
    description: "Configuration to build (Release or Debug, see CMAKE_BUILD_TYPE)"
    required: true
    default: "Release"
  version:
    description: "Version of the compiler that is used (latest or min)."
    required: true
    default: "latest"
  optional-dependencies:
    description: "Build the library with optional dependencies (ON or OFF)"
    required: false
    default: "ON"
runs:
  using: "composite"
  steps:
    - name: Install ninja
      shell: pwsh
      run: choco install -y ninja
    - name: Build
      shell: cmd /C call {0}
      run: |
        cd cpp
        mkdir build-win
        cd build-win
        if min==${{ inputs.version }} (
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        ) else (
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        )
        cmake --version
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=${{ inputs.config }} -DMEMILIO_USE_SYSTEM_JSONCPP=${{ inputs.optional-dependencies == 'ON' && 'OFF' || 'ON'}} -DMEMILIO_USE_SYSTEM_HDF5=${{ inputs.optional-dependencies == 'ON' && 'OFF' || 'ON'}}
        cmake --build . -- -j 4
    - name: Upload built test directory
      uses: actions/upload-artifact@v2
      with:
        name: build-cpp-windows-msvc-${{ inputs.version }}-${{ inputs.config }}-${{ inputs.optional-dependencies == 'ON' && 'full' || 'part'}}
        path: cpp/build-win/tests
        retention-days: 1