image: ubuntu:18.04

build:
  stage: build
  before_script:
     - apt-get -qq update && apt -qq -y install make cmake g++ git doxygen
  script:
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=../epidemiology-current ..
    - cmake --build .
    - cmake --build . --target install
  artifacts:
    expire_in: 2 hrs
    paths:
      - build/
      - epidemiology-current/

# run tests using the binary built before
test:
  stage: test
  script:
    - cd build/tests
    - ./runUnitTests --gtest_output="xml:report.xml"
  artifacts:
    reports:
      junit: build/tests/report.xml


package:
  stage: deploy
  dependencies:
    - build
  script:
    - tar czf epidemiology-current.tar.gz epidemiology-current
  artifacts:
    paths:
      - epidemiology-current.tar.gz
