name: "📚 Documentation"
description: "Report Documentation Issues."
labels:
  - "class::documentation"
body:
- type: markdown
  attributes:
    value: "Please check our [existing issues](https://github.com/SciCompMod/memilio/issues) beforehand."
- type: textarea
  id: doc-description
  attributes:
    label: "Provide a description of requested documentation changes."
  validations:
    required: true
