name: "⭐️ Feature"
description: "Use this template to describe a new Feature of MEmilio"
title: "[Feature]"
body:
- type: markdown
  attributes:
    value: "Please check our [existing issues](https://github.com/DLR-SC/memilio/issues) beforehand."
- type: textarea
  id: Feature-description
  attributes:
    label: "Feature description"
    description: "Describe the Feature."
  validations:
    required: true

- type: textarea
  id: -context
  attributes:
    label: "Additional context"
    description: "Code location/examples, Papers, Mathematics, put them here."

- type: checkboxes
  id: checks
  attributes:
    label: Checklist
    description: Add Labels and add this issue to a project.
    options:
      - label: Attached labels, especially model and loc labels.
        required: false
      - label: Linked to project.
        required: false