# experimental pipeline to test benchmarks on github runners

name: abm_benchmark_test

on:
  schedule:
    - cron: "0 3,9,15,21 * * *" #every day on a few different hours
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-build
        with:
          compiler: gcc
          config: Release
          version: latest
          build-tests: "OFF"
          build-benchmarks: "ON"
          
  bench:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-benchmark
        with:
          build-artifact: build-cpp-linux-gcc-latest-Release-full
