name: Minimal-CI

on:
  schedule:
    - cron: "0 3 * * 0"
  workflow_dispatch:

jobs:
  build-cpp-gcc_clang:
    strategy:
      matrix:
        compiler: ["gcc", "clang"]  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-build
        with: 
          compiler: ${{ matrix.compiler }}
          config: "Debug"
          version: "latest"

  build-cpp-msvc:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-build
        with: 
          config: "Debug"
          version: "latest"

  test-cpp-gcc_clang:
    needs: build-cpp-gcc_clang
    strategy:
      matrix:
        compiler: ["gcc", "clang"]      
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-test
        with: 
          build-artifact: build-cpp-linux-${{ matrix.compiler }}-latest-Debug-full

  test-cpp-msvc:
    needs: build-cpp-msvc
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-test
        with: 
          build-artifact: build-cpp-windows-msvc-latest-Debug-full

  build-py-epidata:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: epidata

  test-py-epidata:
    needs: build-py-epidata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with: 
          package: epidata
  
  build-py-simulation:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: simulation

  test-py-simulation:
    needs: build-py-simulation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with: 
          package: simulation

  build-py-surrogatemodel:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-py
        with:
          package: surrogatemodel

  test-py-surrogatemodel:
    needs: [build-py-surrogatemodel, build-py-simulation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/test-py
        with: 
          package: surrogatemodel

  test-pylint-epidata:
    needs: build-py-epidata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-pylint
        with:
          package: epidata
          
  test-docs:
    needs: build-py-epidata
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-docs
